name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and test
        run: mvn clean verify -P dev

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: (success() || failure()) && github.actor != 'dependabot[bot]'
        with:
          name: Test report          
          path: '**/surefire-reports/**/*.xml'    
          reporter: java-junit

      - name: Publish test coverage
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-coverage
          path: target/site/jacoco
